# LLM-Sentinel Configuration

server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

privacy:
  enabled: true
  detectors:
    - all  # Enable all 50+ detectors
  masking:
    type: deterministic
    format: "[MASKED_{{TYPE}}]"
  header_scrubbing:
    enabled: true
    headers:
      - authorization
      - x-api-key
      - cookie
      - x-auth-token
    preserve_upstream_auth: true  # Allow auth headers for upstream API calls

security:
  enabled: true
  mode: log  # block, log, or passthrough
  rate_limit:
    enabled: true
    requests_per_min: 60
    max_request_size: 1048576  # 1MB
    burst_limit: 10
  vector_security:
    enabled: true
    service_type: "pattern"  # Options: "ml" (best), "pattern" (balanced), "hash" (fast)
    block_threshold: 0.70  # Block at 70% confidence
    max_batch_size: 32
    embedding:
      service_type: "pattern"
      redis_enabled: true   # Enable Redis caching for ML service
      redis_url: "localhost:6379"
      redis_db: 0
      model:
        model_name: "all-MiniLM-L6-v2"  # Pattern-based embeddings with contextual analysis
        model_path: ""
        tokenizer_path: ""
        vocab_path: ""
        cache_dir: "./models"
        auto_download: true  # Enable for pattern embedding service
        max_length: 512
        batch_size: 16  # Smaller batch for pattern embedding
        model_timeout: 30s
    database:
      database_url: "postgres://sentinel:sentinel_pass@localhost:5432/llm_sentinel?sslmode=disable"
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 1h
      conn_max_idle_time: 30m

upstream:
  openai: https://api.openai.com
  anthropic: https://api.anthropic.com
  ollama: http://localhost:11434
  timeout: 30s

logging:
  level: info
  format: json
  file:
    enabled: false
    path: logs/sentinel.log
    max_size: 100  # MB
    max_age: 30    # days
    compress: true

websocket:
  enabled: true
  path: /ws
  max_connections: 100
  read_buffer_size: 1024
  write_buffer_size: 1024
  ping_interval: 54s
  pong_timeout: 60s
  write_timeout: 10s
  max_message_size: 512
  allowed_origins:
    - "*"  # Allow all origins for development
  events:
    broadcast_pii_detections: true
    broadcast_vector_security: true
    broadcast_system: true
    broadcast_connections: true
